# Generated by Django 4.0.5 on 2022-06-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0002_remove_listjob_job_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listjob',
            name='tags',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
