# Generated by Django 4.0.5 on 2022-06-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0004_remove_listjob_category_listjob_catgory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listjob',
            name='catgory',
        ),
        migrations.AddField(
            model_name='listjob',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='postjob.category'),
        ),
    ]
