# Generated by Django 4.0.5 on 2022-06-23 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0008_alter_listjob_posted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listjob',
            name='logo',
            field=models.ImageField(default='/i.jpg', upload_to='logo'),
        ),
    ]
