# Generated by Django 4.0.5 on 2022-06-23 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postjob', '0010_alter_listjob_employer_alter_listjob_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listjob',
            name='logo',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='logo'),
        ),
    ]
