# Generated by Django 4.0.5 on 2022-06-21 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0014_delete_move'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('deadline', models.CharField(blank=True, max_length=50, null=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(default='resume', upload_to='resume')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='userprofile.employeeprofile')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'application',
                'managed': True,
            },
        ),
    ]
