# Generated by Django 4.0.5 on 2022-06-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0005_alter_application_employer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='employer',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='listjob',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
