# Generated by Django 4.0.5 on 2022-06-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapplication', '0007_remove_application_job_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='display',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
