# Generated by Django 4.1.5 on 2023-01-14 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'category',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConfidoJobinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(max_length=50)),
                ('copyright_year', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Listjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('job_location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('tags', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(max_length=50)),
                ('deadline', models.DateField()),
                ('logo', models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='logo')),
                ('website', models.URLField(blank=True, null=True)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('published', models.BooleanField(blank=True, null=True)),
                ('display', models.BooleanField(blank=True, default=True, null=True)),
                ('closed', models.BooleanField(blank=True, null=True)),
                ('featured', models.BooleanField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.category')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.employerprofile')),
            ],
            options={
                'verbose_name': 'Listjob',
                'verbose_name_plural': 'Listjob',
                'db_table': 'listjob',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listjob', models.CharField(blank=True, max_length=250, null=True)),
                ('employer', models.CharField(blank=True, max_length=250, null=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('gender', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('job_location', models.CharField(max_length=100)),
                ('salary', models.CharField(max_length=50)),
                ('display', models.BooleanField(blank=True, default=True, null=True)),
                ('cover_letter', models.TextField()),
                ('resume', models.FileField(default='resume', upload_to='resume')),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userprofile.employeeprofile')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
                'db_table': 'application',
                'managed': True,
            },
        ),
    ]
