# Generated by Django 4.0.5 on 2022-06-06 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('keyword', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='logo')),
                ('banner1', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('banner2', models.ImageField(blank=True, null=True, upload_to='banner')),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(max_length=50)),
                ('copyright_year', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'CompanyProfile',
                'verbose_name_plural': 'CompanyProfile',
                'db_table': 'companyprofile',
                'managed': True,
            },
        ),
    ]
