# Generated by Django 4.0.5 on 2022-06-06 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyProfile',
            new_name='ManuJobinfo',
        ),
        migrations.AlterModelOptions(
            name='manujobinfo',
            options={'managed': True, 'verbose_name': 'ManuJobinfo', 'verbose_name_plural': 'ManuJobinfo'},
        ),
        migrations.AlterModelTable(
            name='manujobinfo',
            table='manujobinfo',
        ),
    ]
