# Generated by Django 4.0.5 on 2022-07-22 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_companyprofile_manujobinfo_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ManuJobinfo',
            new_name='ConfidoJobinfo',
        ),
        migrations.AlterModelOptions(
            name='confidojobinfo',
            options={'managed': True, 'verbose_name': 'ConfidoJobinfo', 'verbose_name_plural': 'ConfidoJobinfo'},
        ),
        migrations.AlterModelTable(
            name='confidojobinfo',
            table='confidojobinfo',
        ),
    ]
