# Generated by Django 4.0.5 on 2022-06-10 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_rename_company_address_employeeprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeprofile',
            name='username',
            field=models.CharField(default='a', max_length=50),
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='username',
            field=models.CharField(default='a', max_length=50),
        ),
    ]
