# Generated by Django 4.0.5 on 2022-06-10 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_employeeprofile_username_employerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employerprofile',
            name='username',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
