# Generated by Django 4.0.5 on 2022-06-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0005_alter_employerprofile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='username',
            field=models.CharField(default=1, max_length=50),
        ),
    ]
