# Generated by Django 4.0.5 on 2022-06-10 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0007_alter_employeeprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
