# Generated by Django 4.0.5 on 2022-06-10 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userprofile', '0008_alter_employeeprofile_username_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='username',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='employerprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(default='a'),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='company_name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
