# Generated by Django 4.0.5 on 2022-06-10 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0009_rename_username_employerprofile_phone_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employerprofile',
            old_name='company_name',
            new_name='company',
        ),
    ]
