# Generated by Django 4.0.5 on 2022-06-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0011_employeeprofile_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='employerprofile',
            name='website',
            field=models.URLField(),
        ),
    ]
