# Generated by Django 4.0.5 on 2022-06-17 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_move'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Move',
        ),
    ]
