# Generated by Django 4.0.5 on 2022-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0014_delete_move'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(default='a', max_length=20),
        ),
    ]
