# Generated by Django 4.0.5 on 2022-06-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_remove_employeeprofile_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeprofile',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
